name: 'Get OpenAPI Spec URL'
description:
  'Retrieves the URL of an OpenAPI spec file from the stack GitHub repository by
  reading the releases and tags.'
author: 'Antoine Wacheux <antoine.wacheux@formance.com>'

# Define your inputs here.
inputs:
  organization:
    description: 'The name of the GitHub organization'
    required: false
    default: 'formancehq'
  repository:
    description: 'The name of the GitHub repository'
    required: false
    default: 'stack'
  token:
    description: 'The GitHub token'
    required: true

# Define your outputs here.
outputs:
  openapi_spec_url:
    description: 'The URL of the OpenAPI spec file'

runs:
  using: node20
  main: dist/index.js
